### ISSUE TITLE
Enable Security Advisories / Security Contact

### ISSUE THREAD

**Issue by R3x** [Reedyuk/write-properties#1]
Hello,

I would like to report a security vulnerability in private, I was not able to find a security contact for this repository and there is no security policy and private reporting is disabled as well. What would be a good contact to reach out to? Or would you be open to enabling private vulnerability reporting for the repository?

**Comment by Reedyuk** [comment]
This is an open source repo, you are welcome to provide a pull request with the suggested change.

**Comment by R3x** [comment]
We (me and my team) are not sending a Pull Request as we feel that it might be misused within the timeframe. We would appreciate it if you can open a security advisory on GitHub.
If you still feel that a pull request is better I can try to do that :)

**Comment by Reedyuk** [comment]
enabled security advisory, please raise it there.

**Comment by R3x** [comment]
Thanks!
